kind: Deployment
apiVersion: apps/v1
metadata:
  name: mq-put-get
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mq-put-get
  template:
    metadata:
      labels:
        app: mq-put-get
    spec:
      volumes:
        - name: certificate-volume
          secret:
            secretName: mq-java-tls-secret
            items:
              - key: mq-java-tls.jks
                path: mq-java-tls.jks
      containers:
        - name: mq-put-get
          image: image-registry.openshift-image-registry.svc:5000/rp/mq-put-get
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: certificate-volume
              readOnly: true
              mountPath: "/app/certs"
          envFrom:
            - configMapRef:
                name: mq-put-get-env-cm
      restartPolicy: Always
