apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: mq-pub-app-build
  labels:
    app: mq-pub
spec:
  source:
    type: Git
    git:
      uri: https://github.com/ragupta2/CloudPakIntegration
    contextDir: "java"
    # sourceSecret:
    #   name: gitsecret
  strategy:
    type: Docker.pub
    dockerStrategy:
      dockerfilePath: Dockerfile.pub # Look for Dockerfile in: gitUri/contextDir/dockerfilePath
  output:
    to:
      kind: ImageStreamTag
      name: mq-pub-app:latest
