apiVersion: v1
kind: Secret
metadata:
  name: tls-secret
type: Opaque
data:
  mq-java-tls.jks: |






# oc create secret generic mq-java-tls-secret --from-file=mq-java-tls.jks=/path/to/mq-java-tls.jks
