kind: Deployment
apiVersion: apps/v1
metadata:
  name: mq-java-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mq-java-app
  template:
    metadata:
      labels:
        app: mq-java-app
    spec:
      volumes:
      - name: certificate-volume
        secret:
          secretName: mq-java-tls-secret
          items:
            - key: mq-java-tls.jks
              path: mq-java-tls.jks
      containers:
        - name: mq-java-app
          image: image-registry.openshift-image-registry.svc:5000/mq-java/mq-java-app
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          volumeMounts:
          - name: certificate-volume
            readOnly: true
            mountPath: "/app/certs"
      restartPolicy: Always
