apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: quickstart-ext-conn-traffic
  namespace: mq
spec:
  host: ext2e-conn.chl.mq.ibm.com
  to:
    kind: Service
    name: mq-nativeha-tls-ibm-mq
  port:
    targetPort: 1414
  tls:
    termination: passthrough