apiVersion: v1
kind: ConfigMap
metadata:
  name: single-inst-ini-cm
data:
  tls.mqsc: |
    DEFINE QLOCAL('IN') REPLACE 
    DEFINE CHANNEL(EXT.CONN4) CHLTYPE(SVRCONN) TRPTYPE(TCP) SSLCAUTH(OPTIONAL) SSLCIPH('ANY_TLS12_OR_HIGHER')
    SET CHLAUTH(EXT.CONN4) TYPE(BLOCKUSER) USERLIST('nobody') ACTION(ADD)
  qm.ini: |
    Channels:
       MQIBindType=FASTPATH
