apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: ext-conn4-traffic
spec:
  host: ext2e-conn4.chl.mq.ibm.com
  to:
    kind: Service
    name: single-inst-ini-persisted-ibm-mq
  port:
    targetPort: 1414
  tls:
    termination: passthrough
