apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: persistent-ini-ext-conn2-traffic
  namespace: mq
spec:
  host: ext2e-conn2.chl.mq.ibm.com
  to:
    kind: Service
    name: nativeha-ini-qm-ibm-mq
  port:
    targetPort: 1414
  tls:
    termination: passthrough