apiVersion: batch/v1
kind: CronJob
metadata:
  name: sample-cronjob
spec:
  schedule: "*/1 * * * *" #runs every min
  # concurrencyPolicy: "Replace"
  # startingDeadlineSeconds: 200
  # suspend: false
  # successfulJobsHistoryLimit: 3
  # failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: default
          containers:
            - name: oc-cli
              image: quay.io/openshift/origin-cli
              command: ["./etc/config/test-script.sh", "sleep 50000000"]
              securityContext:
                privileged: true
              volumeMounts:
                - mountPath: /etc/config
                  name: sample-vol
          volumes:
            - name: sample-vol
              configMap:
                name: test-script
                defaultMode: 0777
          restartPolicy: OnFailure
