apiVersion: mq.ibm.com/v1beta1
kind: QueueManager
metadata:
  name: pubsub-qm
  namespace: mq
spec:
  securityContext:
    supplementalGroups:
      - 99
  license:
    accept: true
    license: L-RJON-C7QG3S
    use: NonProduction
  pki:
    keys:
      - secret:
          items:
            - tls.key
            - tls.crt
          secretName: pubsub-mq-tls-secret
        name: default
  web:
    enabled: true
  version: 9.2.4.0-r1
  template:
    pod:
      containers:
        - env:
            - name: MQSNOAUT
              value: 'yes'
          name: qmgr
  queueManager:
    debug: true
    resources:
      limits:
        cpu: 500m
        memory: 2Gi
      requests:
        cpu: 500m
        memory: 1Gi
    name: PUBSUBQM
    mqsc:
      - configMap:
          items:
            - pub-sub.mqsc
          name: pub-sub-configmap
    availability:
      type: NativeHA
      defaultClass: ibmc-block-gold
      persistedData:
        class: ibmc-block-gold
        deleteClaim: true
        enabled: true
        size: 2Gi
        type: persistent-claim
      queueManager:
        class: ibmc-block-gold
        deleteClaim: true
        type: persistent-claim
        size: 2Gi
      recoveryLogs:
        class: ibmc-block-gold
        deleteClaim: true
        enabled: true
        type: persistent-claim
        size: 2Gi