apiVersion: v1
kind: ConfigMap
metadata:
  name: mq-nativeha-tls-persistent-configmap
data:
  tls.mqsc: |
    DEFINE QLOCAL('IN') REPLACE 
    DEFINE CHANNEL(EXT.CONNRP) CHLTYPE(SVRCONN) TRPTYPE(TCP) SSLCAUTH(OPTIONAL) SSLCIPH('ANY_TLS12_OR_HIGHER') SCYDATA('FN=/opt/mqm/exits/blockip.txt;') SCYEXIT('BlockIP2(BlockExit)')
    SET CHLAUTH(EXT.CONNRP) TYPE(BLOCKUSER) USERLIST('nobody') ACTION(ADD)
