apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: persistent-ext-connrp-traffic
spec:
  host: ext2e-connrp.chl.mq.ibm.com
  to:
    kind: Service
    name: mq-nativeha-tls-persistent-ibm-mq
  port:
    targetPort: 1414
  tls:
    termination: passthrough
