apiVersion: mq.ibm.com/v1beta1
kind: QueueManager
metadata:
  name: mq-nativeha-tls-persistent
spec:
  license:
    accept: true
    license: L-RJON-C7QG3S
    use: NonProduction
  pki:
    keys:
      - secret:
          items:
            - tls.key
            - tls.crt
          secretName: sender-mq-tls-secret
        name: default
  web:
    enabled: true
  version: 9.2.4.0-r1
  queueManager:
    image: image-registry.openshift-image-registry.svc:5000/rp-sender/new-qm-2:v4
    resources:
      limits:
        cpu: 500m
      requests:
        cpu: 500m
    name: QUICKSTART
    mqsc:
      - configMap:
          items:
            - tls.mqsc
          name: mq-nativeha-tls-persistent-configmap
    availability:
      type: NativeHA
    storage:
      defaultClass: ibmc-block-gold
      persistedData:
        class: ibmc-block-gold
        deleteClaim: true
        enabled: true
        type: persistent-claim
      queueManager:
        class: ibmc-block-gold
        enabled: true
        type: persistent-claim
        deleteClaim: true
      recoveryLogs:
        class: ibmc-block-gold
        enabled: true
        type: persistent-claim
        deleteClaim: true
